import 'package:flutter/material.dart';

enum Sender { user, ai }

/// A single message in the briefing conversation. It may carry an optional
/// rich attachment (a property card or an ROI analytics card).
class ChatMessage {
  const ChatMessage({
    required this.sender,
    this.text,
    this.attachment,
  });

  final Sender sender;
  final String? text;
  final MessageAttachment? attachment;

  bool get isUser => sender == Sender.user;
}

/// Base type for rich content rendered under an AI message.
abstract class MessageAttachment {
  const MessageAttachment();
}

/// A property showcase card: hero image, title, blurb and two headline stats.
class PropertyCard extends MessageAttachment {
  const PropertyCard({
    required this.title,
    required this.description,
    required this.gradient,
    required this.stats,
    this.imageAsset,
  });

  final String title;
  final String description;
  final List<Color> gradient; // painted fallback when [imageAsset] is absent
  final List<PropertyStat> stats;

  /// Optional real render (generated by tool/generate_images.py). Falls back to
  /// the painted [gradient] facade if the asset is missing.
  final String? imageAsset;
}

class PropertyStat {
  const PropertyStat({required this.value, required this.label});
  final String value;
  final String label;
}

/// A floor-plan card: a plan image plus a spec grid (area, price, facing…).
class FloorPlanCard extends MessageAttachment {
  const FloorPlanCard({
    required this.title,
    required this.imageAsset,
    required this.specs,
  });

  final String title;
  final String imageAsset;
  final List<FloorPlanSpec> specs;
}

class FloorPlanSpec {
  const FloorPlanSpec({required this.icon, required this.value, required this.label});
  final IconData icon;
  final String value;
  final String label;
}

/// An analytics card: projected yield, confidence, a small trend line and
/// community scores.
class RoiCard extends MessageAttachment {
  const RoiCard({
    required this.yieldPercent,
    required this.confidence,
    required this.peakLabel,
    required this.baselineLabel,
    required this.trend,
    required this.communityScore,
    required this.grade,
    required this.safetyIndex,
  });

  final String yieldPercent;
  final String confidence;
  final String peakLabel;
  final String baselineLabel;
  final List<double> trend; // 0..1 normalized points
  final String communityScore;
  final String grade;
  final String safetyIndex;
}

/// A quick-reply suggestion chip.
class Suggestion {
  const Suggestion(this.label, this.icon);
  final String label;
  final IconData icon;
}
